stages: 
  # - test
  - deploy

# test: 
#   stage : test
#   image : node:latest
#   script: 
#     - npm install
#     - echo hai

deploy : 
  stage : deploy
  script : 
    - gem install dpl
    - gem install faraday -v 1.8.0
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only: 
    - main
